# Generated by Django 5.2.4 on 2025-08-13 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='posts_likes',
            field=models.IntegerField(default=0),
        ),
    ]
