# Generated by Django 5.2.4 on 2025-08-14 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_user_following_alter_post_post_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='post',
            name='posts_likes',
        ),
        migrations.AddField(
            model_name='post',
            name='posts_likes',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
