# Generated by Django 5.2.4 on 2025-08-14 23:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_alter_post_post_creator_remove_post_posts_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_creation_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 14, 23, 48, 38, 275923, tzinfo=datetime.timezone.utc)),
        ),
    ]
