# Generated by Django 5.2.4 on 2025-08-20 22:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_alter_post_post_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
